In [1]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [2]:
df=pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]
df.sample(5)

      Age  Pclass  SibSp  Parch  Survived
783   NaN       3      1      2         0
743  24.0       3      1      0         0
511   NaN       3      0      0         0
221  27.0       2      0      0         0
495   NaN       3      0      0         0

In [3]:
df.shape

(891, 5)

In [4]:
df.dropna(inplace=True)
df.shape

(714, 5)

In [5]:
X=df.iloc[:,:-1]
X

      Age  Pclass  SibSp  Parch
0    22.0       3      1      0
1    38.0       1      1      0
2    26.0       3      0      0
3    35.0       1      1      0
4    35.0       3      0      0
..    ...     ...    ...    ...
885  39.0       3      0      5
886  27.0       2      0      0
887  19.0       1      0      0
889  26.0       1      0      0
890  32.0       3      0      0

[714 rows x 4 columns]

In [6]:
y=df.iloc[:,-1]
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [7]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

### Applying Feature Construction

In [8]:
X['Family_size']=X['Parch']+X['SibSp']+1

In [9]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [10]:
def myfunc(num):
    if num==1: #means alone
        return 0
    elif num==2: # means small family
        return 1
    else: # means large family
        return 2

In [11]:
myfunc(2)

1

In [12]:
X['Family_type']=X['Family_size'].apply(myfunc)

In [13]:
X

      Age  Pclass  SibSp  Parch  Family_size  Family_type
0    22.0       3      1      0            2            1
1    38.0       1      1      0            2            1
2    26.0       3      0      0            1            0
3    35.0       1      1      0            2            1
4    35.0       3      0      0            1            0
..    ...     ...    ...    ...          ...          ...
885  39.0       3      0      5            6            2
886  27.0       2      0      0            1            0
887  19.0       1      0      0            1            0
889  26.0       1      0      0            1            0
890  32.0       3      0      0            1            0

[714 rows x 6 columns]

In [14]:
X.drop(columns=['Parch','SibSp','Family_size'],inplace=True)

In [15]:
X

      Age  Pclass  Family_type
0    22.0       3            1
1    38.0       1            1
2    26.0       3            0
3    35.0       1            1
4    35.0       3            0
..    ...     ...          ...
885  39.0       3            2
886  27.0       2            0
887  19.0       1            0
889  26.0       1            0
890  32.0       3            0

[714 rows x 3 columns]

In [16]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20))

np.float64(0.7088492063492063)

### Features Splitting

In [17]:
df=pd.read_csv('train.csv')

In [18]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
380,381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
478,479,0,3,"Karlsson, Mr. Nils August",male,22.0,0,0,350060,7.5208,NaN,S
138,139,0,3,"Osen, Mr. Olaf Elon",male,16.0,0,0,7534,9.2167,NaN,S
748,749,0,1,"Marvin, Mr. Daniel Warner",male,19.0,1,0,113773,53.1000,D30,S

In [19]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [22]:
df['Name'].str.split(', ',expand=True)

             0                                           1
0       Braund                             Mr. Owen Harris
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                 Miss. Laina
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)
4        Allen                           Mr. William Henry
..         ...                                         ...
886   Montvila                                 Rev. Juozas
887     Graham                        Miss. Margaret Edith
888   Johnston              Miss. Catherine Helen "Carrie"
889       Behr                             Mr. Karl Howell
890     Dooley                                 Mr. Patrick

[891 rows x 2 columns]

In [23]:
df['Name'].str.split(', ',expand=True)[1]

0                                 Mr. Owen Harris
1      Mrs. John Bradley (Florence Briggs Thayer)
2                                     Miss. Laina
3              Mrs. Jacques Heath (Lily May Peel)
4                               Mr. William Henry
                          ...
886                                   Rev. Juozas
887                          Miss. Margaret Edith
888                Miss. Catherine Helen "Carrie"
889                               Mr. Karl Howell
890                                   Mr. Patrick
Name: 1, Length: 891, dtype: object

In [24]:
df['Name'].str.split(', ',expand=True)[1].str.split('.',expand=True)

        0                                       1     2
0      Mr                             Owen Harris  None
1     Mrs   John Bradley (Florence Briggs Thayer)  None
2    Miss                                   Laina  None
3     Mrs           Jacques Heath (Lily May Peel)  None
4      Mr                           William Henry  None
..    ...                                     ...   ...
886   Rev                                  Juozas  None
887  Miss                          Margaret Edith  None
888  Miss                Catherine Helen "Carrie"  None
889    Mr                             Karl Howell  None
890    Mr                                 Patrick  None

[891 rows x 3 columns]

In [26]:
df['Name'].str.split(', ',expand=True)[1].str.split('.',expand=True)[0]

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: object

In [28]:
df['Title']=df['Name'].str.split(', ',expand=True)[1].str.split('.',expand=True)[0]

In [ ]:
df[['Title','Name']] # now we can do most work on it like, miss> unmarried, mrs> married, Mr survived ration,etc

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [33]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [35]:
df['Is_married'] = 0
df.loc[df['Title'] == 'Mrs', 'Is_married'] = 1

In [36]:
df['Is_married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64