In [102]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [ ]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9) #every time you run the code, the same 5 rows are selected
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [104]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [105]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\MY\AppData\Local\Temp\ipykernel_22212\766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\MY\AppData\Local\Temp\ipykernel_22212\766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\MY\AppData\Local\Temp\ipykernel_22212\766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [106]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [107]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [108]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [109]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [110]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [111]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [112]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [113]:
df1.iloc[1,0] = 23.14

In [114]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [115]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [116]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [117]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [118]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [119]:
df1.iloc[3,1] = 11.06

In [120]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [121]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [122]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [123]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [124]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [125]:
df1.iloc[4,-1] = 31.56

In [126]:
# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [127]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [128]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [129]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [130]:
df2.iloc[1,0] = 23.78

In [131]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [132]:
df2.iloc[3,1] = 11.22

In [133]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [134]:
df2.iloc[4,-1] = 31.56

In [135]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [136]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [137]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.22            26.00
44        2.0           15.00            31.56

In [138]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([24.57698058])

In [139]:
df3.iloc[1,0] = 24.57

In [140]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.37282844])

In [141]:
df3.iloc[3,1] = 11.37

In [142]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([45.53976417])

In [143]:
df3.iloc[4,-1] = 45.53

In [144]:
df2.iloc[3,1] = 11.22

In [145]:
df3

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      24.57            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.37            26.00
44       2.00           15.00            45.53

In [146]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.79            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.15             0.00
44       0.00            0.00            13.97

In [147]:
df4 = df3.copy()
df4.iloc[1,0] = np.nan
df4

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.37            26.00
44        2.0           15.00            45.53

In [148]:
X=df4.iloc[[0,2,3,4],[1,2]]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.37            26.00
44           15.00            45.53

In [149]:
y=df4.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [150]:
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[1,[1,2]].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([26.98977176])

In [152]:
df4.iloc[1,0] = 26.98
df4

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      26.98            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.37            26.00
44       2.00           15.00            45.53

In [153]:
df4.iloc[3,1] = np.nan
df4

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      26.98             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            45.53

In [154]:
X=df4.iloc[[0,1,2,4],[0,2]]
y=df4.iloc[[0,1,2,4],1]
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12.74923997])

In [155]:
df4.iloc[3,1] = 12.74
df4

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      26.98            5.00            20.00
2       15.00           10.00            41.00
14      12.00           12.74            26.00
44       2.00           15.00            45.53

In [156]:
df4.iloc[4,-1] = np.nan
X=df4.iloc[0:4,0:2]
y=df4.iloc[0:4,-1]
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[4,0:2].values.reshape(1,2))

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([68.71345168])

In [157]:
df4.iloc[4,-1] = 68.71
df4

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      26.98            5.00            20.00
2       15.00           10.00            41.00
14      12.00           12.74            26.00
44       2.00           15.00            68.71

In [158]:
df4-df3

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       2.41            0.00             0.00
2        0.00            0.00             0.00
14       0.00            1.37             0.00
44       0.00            0.00            23.18

In [159]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Initial mean imputation
df_current = df0.copy()

tol = 0.001
max_iter = 100

for iteration in range(max_iter):

    df_new = df_current.copy()

    # -------------------------
    # Impute R&D Spend
    # -------------------------
    df_new.iloc[1,0] = np.nan

    X = df_new.iloc[[0,2,3,4],[1,2]]
    y = df_new.iloc[[0,2,3,4],0]

    lr = LinearRegression()
    lr.fit(X,y)

    pred = lr.predict(df_new.iloc[1,[1,2]].values.reshape(1,-1))[0]
    df_new.iloc[1,0] = pred

    # -------------------------
    # Impute Administration
    # -------------------------
    df_new.iloc[3,1] = np.nan

    X = df_new.iloc[[0,1,2,4],[0,2]]
    y = df_new.iloc[[0,1,2,4],1]

    lr = LinearRegression()
    lr.fit(X,y)

    pred = lr.predict(df_new.iloc[3,[0,2]].values.reshape(1,-1))[0]
    df_new.iloc[3,1] = pred

    # -------------------------
    # Impute Marketing Spend
    # -------------------------
    df_new.iloc[4,2] = np.nan

    X = df_new.iloc[0:4,0:2]
    y = df_new.iloc[0:4,2]

    lr = LinearRegression()
    lr.fit(X,y)

    pred = lr.predict(df_new.iloc[4,0:2].values.reshape(1,-1))[0]
    df_new.iloc[4,2] = pred

    # -------------------------
    # Check convergence
    # -------------------------
    diff = abs(df_new - df_current)

    print(f"\nIteration {iteration+1}")
    print(df_new)
    print("\nDifference")
    print(diff)

    if diff.max().max() < tol:
        print(f"\nConverged after {iteration+1} iterations")
        break

    df_current = df_new.copy()

print("\nFinal Imputed DataFrame")
print(df_current)

Iteration 1
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.141587        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.063618        26.000000
44   2.000000       15.000000        31.601847

Difference
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  13.891587        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.186382         0.000000
44   0.000000        0.000000         2.351847

Iteration 2
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.828703        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.230737        26.000000
44   2.000000       15.000000        39.390436

Difference
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.687117        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.167119         0.000000
44   0.000000        0.000000         7.788589

Iteration 3
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.887784        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       12.275798        26.000000
44   2.000000       15.000000        63.339357

Difference
    R&D Spend  Administration  Marketing Spend
21    0.00000         0.00000          0.00000
37    3.05908         0.00000          0.00000
2     0.00000         0.00000          0.00000
14    0.00000         1.04506          0.00000
44    0.00000         0.00000         23.94892

Iteration 4
    R&D Spend  Administration  Marketing Spend
21     8.0000       15.000000        30.000000
37    26.6489        5.000000        20.000000
2     15.0000       10.000000        41.000000
14    12.0000       13.064888        26.000000
44     2.0000       15.000000        70.952205

Difference
    R&D Spend  Administration  Marketing Spend
21   0.000000         0.00000         0.000000
37   0.238884         0.00000         0.000000
2    0.000000         0.00000         0.000000
14   0.000000         0.78909         0.000000
44   0.000000         0.00000         7.612848

Iteration 5
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.721335        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.020439        26.000000
44   2.000000       15.000000        70.679851

Difference
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.072435        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.044449         0.000000
44   0.000000        0.000000         0.272354

Iteration 6
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.718225        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.022458        26.000000
44   2.000000       15.000000        70.692637

Difference
    R&D Spend  Administration  Marketing Spend
21    0.00000        0.000000         0.000000
37    0.00311        0.000000         0.000000
2     0.00000        0.000000         0.000000
14    0.00000        0.002019         0.000000
44    0.00000        0.000000         0.012787

Iteration 7
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.718371        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.022364        26.000000
44   2.000000       15.000000        70.692041

Difference
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.000146        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.000094         0.000000
44   0.000000        0.000000         0.000597

Converged after 7 iterations

Final Imputed DataFrame
    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.718225        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.022458        26.000000
44   2.000000       15.000000        70.692637

C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\MY\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [161]:
print("Final Imputed DataFrame:")
print(np.round(df_current, 2))

Final Imputed DataFrame:
    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      26.72            5.00            20.00
2       15.00           10.00            41.00
14      12.00           13.02            26.00
44       2.00           15.00            70.69