In [52]:
import numpy as np
import pandas as pd

In [53]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [54]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [55]:
date.info() # date is object should be date so

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [56]:
# Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [57]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [58]:
date['date_year']=date['date'].dt.year

In [59]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### 1. Extract month

In [60]:
date['date_mon']=date['date'].dt.month

In [61]:
date.head()

        date  product_id  city_id  orders  date_year  date_mon
0 2019-12-10        5628       25       3       2019        12
1 2018-08-15        3646       14     157       2018         8
2 2018-10-23        1859       25       1       2018        10
3 2019-08-17        7292       25       1       2019         8
4 2019-01-06        4344       25       3       2019         1

In [62]:
# month name
date['date_mon_name']=date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  date_mon date_mon_name
0 2019-12-10        5628       25       3       2019        12      December
1 2018-08-15        3646       14     157       2018         8        August
2 2018-10-23        1859       25       1       2018        10       October
3 2019-08-17        7292       25       1       2019         8        August
4 2019-01-06        4344       25       3       2019         1       January

### 1. Extract days

In [63]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_mon,date_mon_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [64]:
# day of week
date['date_dow']=date['date'].dt.day_of_week
date.head()

,date,product_id,city_id,orders,date_year,date_mon,date_mon_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [65]:
# day of week name
date['date_dow_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_mon,date_mon_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [66]:
# is weekend?
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mon,date_mon_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### Extract week of the year

In [67]:
date['date_week']=date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mon,date_mon_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### Extract Quarter

In [68]:
date['quarter']=date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mon,date_mon_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### Extract Semester

In [69]:
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).sample(5)

,date,date_year,date_mon,date_mon_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
843,2019-02-14,2019,2,February,14,3,Thursday,0,7,1,1
770,2018-09-10,2018,9,September,10,0,Monday,0,37,3,2
6,2018-11-21,2018,11,November,21,2,Wednesday,0,47,4,2
938,2019-06-21,2019,6,June,21,4,Friday,0,25,2,1
559,2019-11-16,2019,11,November,16,5,Saturday,1,46,4,2

### Extract Time elapsed between dates

In [70]:
import datetime

In [71]:
today=datetime.datetime.today()
today

datetime.datetime(2026, 5, 10, 13, 58, 17, 26214)

In [72]:
today-date['date']

0     2343 days 13:58:17.026214
1     2825 days 13:58:17.026214
2     2756 days 13:58:17.026214
3     2458 days 13:58:17.026214
4     2681 days 13:58:17.026214
                 ...
995   2771 days 13:58:17.026214
996   2712 days 13:58:17.026214
997   2560 days 13:58:17.026214
998   2625 days 13:58:17.026214
999   2399 days 13:58:17.026214
Name: date, Length: 1000, dtype: timedelta64[ns]

In [73]:
(today-date['date']).dt.days

0      2343
1      2825
2      2756
3      2458
4      2681
       ...
995    2771
996    2712
997    2560
998    2625
999    2399
Name: date, Length: 1000, dtype: int64

In [74]:
# month passed
np.round((today - date['date']).dt.days / 30, 0) # here dt.days count total days, then divide by 30 
# to get months and round 0 means 2.4== 2

0      78.0
1      94.0
2      92.0
3      82.0
4      89.0
       ...
995    92.0
996    90.0
997    85.0
998    88.0
999    80.0
Name: date, Length: 1000, dtype: float64

# Time

In [75]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [76]:
# Converting to datetime datatype
time['date']=pd.to_datetime(time['date'])

In [77]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [78]:
time['hrs']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second
time.head()

,date,msg,hrs,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time part

In [80]:
time['time']=time['date'].dt.time
time.head()

,date,msg,hrs,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [81]:
today-time['date']

0     4529 days 13:08:17.026214
1     4393 days 14:18:17.026214
2     4879 days 13:37:17.026214
3     4181 days 13:27:17.026214
4     4578 days 14:47:17.026214
                 ...
995   5168 days 13:08:17.026214
996   4489 days 14:44:17.026214
997   4954 days 14:21:17.026214
998   5070 days 14:24:17.026214
999   4342 days 14:33:17.026214
Name: date, Length: 1000, dtype: timedelta64[ns]

In [84]:
(today-time['date']).dt.days

0      4529
1      4393
2      4879
3      4181
4      4578
       ...
995    5168
996    4489
997    4954
998    5070
999    4342
Name: date, Length: 1000, dtype: int64

In [85]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.913529e+08
1      3.796067e+08
2      4.215946e+08
3      3.612868e+08
4      3.955924e+08
           ...
995    4.465625e+08
996    3.879027e+08
997    4.280773e+08
998    4.380999e+08
999    3.752012e+08
Name: date, Length: 1000, dtype: float64

In [86]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.522548e+06
1      6.326778e+06
2      7.026577e+06
3      6.021447e+06
4      6.593207e+06
           ...
995    7.442708e+06
996    6.465044e+06
997    7.134621e+06
998    7.301664e+06
999    6.253353e+06
Name: date, Length: 1000, dtype: float64

In [87]:
# in hours
(today - time['date'])/np.timedelta64(1,'h')

0      108709.138063
1      105446.304730
2      117109.621396
3      100357.454730
4      109886.788063
           ...
995    124045.138063
996    107750.738063
997    118910.354730
998    121694.404730
999    104222.554730
Name: date, Length: 1000, dtype: float64